'''

This code is used to reform the MD2020 generated by MATLAB from .mat to .pkl,

and the reformed MD2020 is available for the function gendata() in the provided code for SCNN.

'''
import scipy.io as sc
import numpy as np
dict = {}
mode = ["BPSK", "QPSK", "8PSK", "16QAM", "64QAM", "PAM4","GFSK" ,"CPFSK" ,"B-FM", "DSB-AM" ,"SSB-AM"]
for i in mode:
    for j in range(-6,31,4):
        data = sc.loadmat(r"D:\MATLAB\Examples\R2020a\deeplearning_shared\ModulationClassificationWithDeepLearningExample\datasets\{}{}db.mat".format(i,j))
        data = data["frame_list"]
        data_k = [np.array([data[k].real,data[k].imag]) for k in range(400)]
        data_tmp = np.stack(data_k)
        dict[(i.encode('ascii'),j)]=data_tmp
import pickle
def save_obj(obj, name):
    with open('./'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)
save_obj(dict, 'MD2020_Version_V')
